import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import "@fontsource/roboto/400.css";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";

const roboto = Roboto({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Golden Perfume",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
        />
      </head>

      <body className={roboto.className}>{children}</body>
    </html>
  );
}
